### ISSUE TITLE
README Clarification needed

### ISSUE THREAD

**Issue by theAkito** [relaytools/spamblaster#1]
Greetings! 👋🏻

Thank you for this piece of software.

I would like to set it up, but I'm struggling to understand specific parts of the configuration.

For example, what is the `relay.tools` API? I have searched everywhere, including everything from [hoytech/strfry](https://github.com/hoytech/strfry) & I did not find a single reference to this.
Is it something built into `strfry`?
Where is this documented?

How would the URL look like, usually?

Like this, except with a different relay ID?

https://github.com/relaytools/spamblaster/blob/5107a3fba7c5c7927fa51da460198359d1968bfe/main.go#L167

Thank you!

**Comment by jeremyd** [comment]
Hi there!

The relay.tools API is something that I run.  It's accessible via https://nostr1.com or https://relay.tools.  Yes, if you signup on there you can use the id from the URL to your relay here in this config.

like: https://relay.tools/api/sconfig/relays/yourID

**Comment by jeremyd** [comment]
sorry it took me a while to see this message, I didn't realize I wasn't following the repo notifications.  (but I am now!)

**Comment by jeremyd** [comment]
closed inactive
