### ISSUE TITLE
when pubkey entry is blank, it allows all pubkeys

### ISSUE THREAD

**Issue by jeremyd** [relaytools/spamblaster#11]
This is a bug.  It should not be allowing all or allowing pubkeys.  Need to fix this with form validation upstream and also check for this in spamblaster with secondary validation.

**Comment by SilberWitch** [comment]
It happens when I click on "Add" without entering anything into the "add pubkey" input box.
I don't see my lists, so I'm always looking around for some button to push, to see the lists.

**Comment by SilberWitch** [comment]
The number of npubs allowed keeps fluctuating. It's always higher than what is on the list.

**Comment by jeremyd** [comment]
@SilberWitch I believe you already figured it out, the upgrade for this hotfix, would require deleting the original non-namespace entries, and then importing the list to get the new namespace that includes pubkey.  otherwise you may see this behavior of the old list just stays there un-modified..

**Comment by jeremyd** [comment]
additional fixes for this validation bug UI side, got hung-up in a feature branch .. as they were a mix of PR that I modified and code I had to test and use (branch nip05 soon).. :pray:

**Comment by SilberWitch** [comment]
I'm just added the rest of the team as moderators and we're now editing the list, directly. Do I still need to do something to "tidy up"?

**Comment by jeremyd** [comment]
I think you're all good.  Also, there's been further code merged that fixes up the validation on pubkey inputs.
