### ISSUE TITLE
Publish relay events for NIP-29 groups

### ISSUE THREAD

**Issue by Silberengel** [relaytools/spamblaster#12]
So that we can use something like https://chat29.pages.dev/ from our read-restricted project team relay? We're still stuck on Slack.

https://github.com/nostr-protocol/nips/blob/simple-chat-groups/29.md

**Comment by jeremyd** [comment]
tracking the progress of this nip29, thank u for the feedback.  Any other good nip29 clients yet?

**Comment by SilberWitch** [comment]
Haven't seen any. 🤷🏻‍♀️
