### ISSUE TITLE
Writing Kind 01 note in replies sorta flakey

### ISSUE THREAD

**Issue by SilberWitch** [relaytools/spamblaster#5]
Writing notes directly to https://theforest.nostr1.com/ seems to work smoothly, but I sometimes have trouble writing a note one level down. It's worst when the field loses focus, I think, such as when I have the keyboard open and type the note, on mobile. I have more success, if I close the keyboard before clicking Send.

![image](https://github.com/user-attachments/assets/342b9311-5547-4e31-9387-2add1d043b38)

**Comment by jeremyd** [comment]
I'll see what I can do about getting better text input here.  Was this IOS or Android?

**Comment by SilberWitch** [comment]
Android 11

**Comment by SilberWitch** [comment]
I think the problem is that something is losing focus, rather than something being hidden. I can see the reply button, but when I hit it, it doesn't do respond. I have to close the keyboard and touch the field and then hit reply.

Might just be my phone being weird, but I wanted to report it, in case it's a more universal issue.

**Comment by jeremyd** [comment]
ah, ok!  I know what to look for now.. I have seen this I think.  Perhaps I can make it send when enter key is pressed like the main dialog does.

**Comment by jeremyd** [comment]
changes to replies were made to match the post screen (multi-line) and switch to a form style which I think is helping.  if not re-open this.
