### ISSUE TITLE
Option to pull in profiles

### ISSUE THREAD

**Issue by SilberWitch** [relaytools/spamblaster#6]
I'm often looking at an entirely anon thread, which is fun for a while, but an option to pull in active or recent profiles to an AUTH private relay, would be nice.

**Comment by jeremyd** [comment]
agree, ok I'll see what I can do here..  there's a couple of options.

**Comment by SilberWitch** [comment]
I think this might be complete. :thinking:

**Comment by jeremyd** [comment]
It appears to be working really well, yes I think we can close it.
