### ISSUE TITLE
Please give me a wider input box

### ISSUE THREAD

**Issue by SilberWitch** [relaytools/spamblaster#8]
The "say something" box at the top of the screen is hard-limited to a mobile width and doesn't expand vertically, so I can only ever see a few words at a time. I've been typing blindly or writing someplace else and then copy-pasting in, but a maximizer would be nice.

Like so
![expandable field](https://i.sstatic.net/dj7oC.png)

**Comment by jeremyd** [comment]
good idea yeah, I'll keep this in mind along with the reply box, try to get a better text widget going for both.

**Comment by jeremyd** [comment]
deployed some changes, textarea now expands vertically and auto wraps longer lines in both reply and post.  got rid of enter being post but added shift-enter for PC posting hotkey.  lemme know what you think, and if the reply still seems buggy or not.

https://github.com/relaytools/relaycreator/pull/9
